version: '3.1'

services:
  covid-db:
    image: postgres:14.6-alpine
    container_name: covid-db
    restart: always
    environment:
      POSTGRES_USER: postgres # identifiant de la BDD
      POSTGRES_PASSWORD: betabeta # mdp de la BDD
      POSTGRES_DB: covid-db
    ports:
      - 5432:5432

  covid-api:
    image: covid-api-image
    container_name: covid-api
    user: 1000:1000
    ports:
      - 8080:8080 # port utilisé par l'api